openapi: 3.0.0
info:
  title: Wonderbites App
  description: ""
  version: v1.0
  license:
    name: MIT
    url: https://api.wonderbites.app
security:
  - BearerAuth: []
servers:
  - description: Wonderbites API for public website and mobile applications.
    url: https://api.wonderbites.app/api

tags:
  - name: Auth
    description: Application authentication endpoints.
  - name: Auth > User
    description: Application authentication endpoints.
  - name: User
    description: Application authentication endpoints.
  - name: User > Profile
    description: Application authentication endpoints.
  - name: Cart
  - name: Cart > Products
  - name: Cart > Ingridients
  - name: Cart > Wonderpoints
  - name: Cuisine
  - name: Wishlist
  - name: Wishlist > Products
  - name: Wishlist > Ingridients
  - name: Product
  - name: Coupon
  - name: Auth > Content Pages
  - name: Wishlists
  - name: Category
  - name: Profile
  - name: Profile > Addresses
  - name: Orders
  - name: Reviews
  - name: Advertisement
  - name: Pages
  - name: Media
paths:
  /login:
    post:
      tags:
        - Auth
      security: []
      summary: Login
      description: Login users via their email|mobile and password.
      operationId: loginToApp
  /register:
    post:
      tags:
        - Auth
      security: []
      summary: Register
      description: Register users to the wonderbites cloud.
      operationId: registerToApp
  /logout:
    post:
      tags:
        - Auth
      security:
        - BearerAuth:
            - token:revoke
      summary: Logout
      description: Revoke logged in user's auth token.
      operationId: logoutFromApp
  /users/auth:
    get:
      tags:
        - User
      security:
        - BearerAuth:
            - auth:view
      summary: Current
      description: Get the authenticated user data based on the authentication token.
      operationId: authenticatedUser
  /users/avatar:
    put:
      tags:
        - User
      security:
        - BearerAuth:
            - avatar:update
      summary: Avatar
      description: Update user's profile avatar.
      operationId: userAvatar
  /users/{id}:
    put:
      tags:
        - User > Profile
      security:
        - BearerAuth:
            - auth:update
      summary: Update Profile
      description: Update user profile data.
      operationId: updateUserByID
    get:
      tags:
        - Users
      security:
        - BearerAuth:
            - auth:view
      summary: User Profile
      description: Get the authenticated user data based on the authentication token.
      operationId: showUserByID
  /addresses:
    get:
      tags:
        - Addresses
      security:
        - BearerAuth:
            - address:list
      summary: Browse Addresses
      operationId: getAddressesList
    post:
      tags:
        - Addresses
      security:
        - BearerAuth:
            - address:create
      summary: Create Address
      operationId: storeAddressesList
  /addresses/{id}:
    get:
      tags:
        - Addresses
      security:
        - BearerAuth:
            - address:view
      summary: View Address
      operationId: getAddressesById
    put:
      tags:
        - Addresses
      security:
        - BearerAuth:
            - address:edit
            - address:update
      summary: Update Address
      operationId: putAddressesById
    patch:
      tags:
        - Addresses
      security:
        - BearerAuth:
            - address:edit
            - address:update
      summary: Update Address
      operationId: patchAddressesById
    delete:
      tags:
        - Addresses
      security:
        - BearerAuth:
            - address:delete
            - address:destroy
      summary: Delete Address
      description: Request to delete the user address.
      operationId: deleteAddressesById
  /categories:
    get:
      tags:
        - Categories
      security: []
      summary: List
      description: By passing in the appropriate options, you can search for available categories in the system.
      operationId: searchCategory
  /categories/{id}:
    get:
      tags:
        - Categories
      security: []
      summary: View
      description: By passing in the appropriate options, you can search for available categories in the system.
      operationId: showCategory
  /products:
    get:
      tags:
        - Products
      security: []
      summary: List Products
      description: By passing in the appropriate options, you can search for available categories in the system.
      operationId: searchProducts
  /cart:
    put:
      tags:
        - Cart > Ingridients
      summary: Add
    post:
      tags:
        - Wishlist > Ingridients
      summary: Remove
    get:
      tags:
        - Cart
      summary: Show
  /wonderpoints/avail:
      get:
        tags:
          - Cart > Wonderpoints
        summary: Avail
  /wishlists:
    put:
      tags:
        - Wishlists
      summary: Remove
    post:
      tags:
        - Wishlists
      summary: create
    get:
      tags:
        - Wishlists
      summary: Get
  /coupons/apply:
    post:
      tags:
        - Coupon
      summary: New Request
  /orders:
    get:
      tags:
        - Orders
      summary: List
  /reviews:
    get:
      tags:
        - Reviews
      summary: Store
  /advertisements:
    get:
      tags:
        - Advertisement
      summary: New Request
  /cuisines:
    get:
      tags:
        - Cuisine
      summary: List
  /wonderpoints:
    get:
      tags:
        - Cart > Wonderpoints
      summary: Index
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer