openapi: 3.0.0
info:
  title: Wonderbites App
  description: ""
  version: v1.0
  license:
    name: UNLICENSED
    url: README.md
security:
  - BearerAuth: []
servers:
  - description: Wonderbites API for public website and mobile applications.
    url: https://api.wonderbites.app/api

tags:
  - name: Auth
    description: Application authentication endpoints.
  - name: Auth > OTP
    description: Password less authentication endpoints.
  - name: Categories
    description: Categories endpoints for Android/iOS/Web App.
  - name: Products
    description: Products endpoints for Android/iOS/Web App.
  - name: Cuisines
    description: Cuisines endpoints for Android/iOS/Web App.
  - name: Banners
    description: Banners endpoints for Android/iOS/Web App.
  - name: Checkouts
    description: Checkout endpoints for Android/iOS/Web App.
  - name: Auth > User
    description: Authenticated user.
  - name: User > Profile
    description: Authenticated User Profile.
  - name: User > Avatar
    description: Authenticated User Avatar.
  - name: User > Address
    description: Application authentication endpoints.
  - name: User > Coupons
    description: Application authentication endpoints.
  - name: User > Cart
    description: Application authentication endpoints.
  - name: User > Wonder Points
    description: Application authentication endpoints.
  - name: User > Orders
    description: Application authentication endpoints.
  - name: User > Reviews
    description: Application authentication endpoints.
  - name: User > Feedbacks
    description: Application authentication endpoints.
  - name: User > Wishlist
    description: Application authentication endpoints.
  - name: Media
    description: Application authentication endpoints.
  - name: Static > Pages
    description: Application authentication endpoints.
paths:
  /otp/generate:
    post:
      tags:
        - Auth > OTP
      security: []
      summary: Generate OTP
      description: Request OTP to login.
      operationId: generateOtpToLogin
  /otp/verify/{token}:
    post:
      tags:
        - Auth > OTP
      security: []
      summary: Verify OTP
      description: Verify the received code.
      operationId: verifyVerificationCode
  /otp/login:
    post:
      tags:
        - Auth > OTP
      security: []
      summary: OTP Login
      description: Login with mobile otp.
      operationId: loginToAppViaOTP
  /otp/register:
    post:
      tags:
        - Auth > OTP
      security: []
      summary: OTP Register
      description: Register with mobile otp.
      operationId: registerToAppViaOTP
  /otp/forgot-password:
    post:
      tags:
        - Auth > OTP
      security: []
      summary: OTP / Forgot Password
      description: Forgot password.
      operationId: forgotPasswordViaOTP
  /otp/reset-password/{token}:
    post:
      tags:
        - Auth > OTP
      security: []
      summary: OTP / Reset Password
      description: Reset password.
      operationId: resetPasswordViaOTP
  /login:
    post:
      tags:
        - Auth
      security: []
      summary: Login
      description: Login users via their email|mobile and password.
      operationId: loginToApp
  /register:
    post:
      tags:
        - Auth
      security: []
      summary: Register
      description: Register users to the wonderbites cloud.
      operationId: registerToApp
  /logout:
    post:
      tags:
        - Auth
      security:
        - BearerAuth:
            - token:revoke
      summary: Logout
      description: Revoke logged in user's auth token.
      operationId: logoutFromApp
  /users/auth:
    get:
      tags:
        - Auth > User
      security:
        - BearerAuth:
            - auth:view
      summary: Get
      description: Get the authenticated user data based on the authentication token.
      operationId: authenticatedUser
  /users/avatar:
    put:
      tags:
        - User > Avatar
      security:
        - BearerAuth:
            - avatar:update
      summary: Update
      description: Update user's profile avatar.
      operationId: userAvatar
  /users/{id}:
    put:
      tags:
        - User > Profile
      security:
        - BearerAuth:
            - auth:update
      summary: Update
      description: Update user profile data.
      operationId: updateUserByID
    get:
      tags:
        - User > Profile
      security:
        - BearerAuth:
            - auth:view
      summary: Detail
      description: Get the authenticated user data based on the authentication token.
      operationId: showUserByID
    delete:
      tags:
        - User > Profile
      security:
        - BearerAuth:
            - auth:view
      summary: Delete
      description: Get the authenticated user data based on the authentication token.
      operationId: deleteUserById
  /addresses:
    get:
      tags:
        - User > Address
      security:
        - BearerAuth:
            - address:list
      summary: List
      operationId: getAddressesList
    post:
      tags:
        - User > Address
      security:
        - BearerAuth:
            - address:create
      summary: Create
      operationId: storeAddressesList
  /addresses/{id}:
    get:
      tags:
        - User > Address
      security:
        - BearerAuth:
            - address:view
      summary: Show
      operationId: getAddressesById
    put:
      tags:
        - User > Address
      security:
        - BearerAuth:
            - address:edit
            - address:update
      summary: Update
      operationId: putAddressesById
    patch:
      tags:
        - User > Address
      security:
        - BearerAuth:
            - address:edit
            - address:update
      summary: Update
      operationId: patchAddressesById
    delete:
      tags:
        - User > Address
      security:
        - BearerAuth:
            - address:delete
            - address:destroy
      summary: Delete
      description: Request to delete the user address.
      operationId: deleteAddressesById
  /categories:
    get:
      tags:
        - Categories
      security: []
      summary: List
      operationId: getTheListOfCategories
      description: By passing in the appropriate options, you can search for available categories in the system.
  /categories/{id}:
    get:
      tags:
        - Categories
      security: []
      summary: View
      description: By passing in the appropriate options, you can search for available categories in the system.
      operationId: showCategory
  /products:
    get:
      tags:
        - Products
      security: []
      summary: List
      description: By passing in the appropriate options, you can search for available products in the system.
      operationId: searchProducts
  /products/{id}:
    get:
      tags:
        - Products
      security: []
      summary: Show
      description: By passing in the appropriate options, you can search for available products in the system.
      operationId: showProducts
  /carts/{token}/{id}:
    put:
      tags:
        - User > Cart
      summary: Update
      operationId: addToCartEndpoint
    patch:
      tags:
        - User > Cart
      summary: Update
      operationId: updateCartEndpoint
    get:
      tags:
        - User > Cart
      summary: Get Detail
      operationId: getCartDetails
  /wonder-points:
    get:
      tags:
        - User > Wonder Points
      summary: Detail
      operationId: listEarnedPoints
  /wonder-points/avail:
    get:
      tags:
        - User > Wonder Points
      summary: Balance
      operationId: checkBalancePoints
  /wishlists:
    get:
      tags:
        - User > Wishlist
      summary: Detail
      operationId: getWishlist
    put:
      tags:
        - User > Wishlist
      summary: Update
  /wishlists/clean:
    post:
      tags:
        - User > Wishlist
      summary: Clean
  /feedbacks:
    get:
      tags:
        - User > Feedbacks
      summary: List
    post:
      tags:
        - User > Feedbacks
      summary: Store
  /feedbacks/{id}:
    get:
      tags:
        - User > Feedbacks
      summary: Show
    put:
      tags:
        - User > Feedbacks
      summary: Update
    patch:
      tags:
        - User > Feedbacks
      summary: Update
    delete:
      tags:
        - User > Feedbacks
      summary: Delete
  /coupons/apply:
    post:
      tags:
        - User > Coupons
      summary: Redeem
  /coupons/remove:
    post:
      tags:
        - User > Coupons
      summary: Redeem
  /orders:
    get:
      tags:
        - User > Orders
      summary: List
      operationId: getTheOrdersList
  /orders/{id}:
    get:
      tags:
        - User > Orders
      summary: Detail
      operationId: getTheOrderDetailsByItsID
    put:
      tags:
        - User > Orders
      summary: Cancel
      operationId: orderCancellationRequest
  /reviews:
    get:
      tags:
        - User > Reviews
      summary: List
    post:
      tags:
        - User > Reviews
      summary: Store
  /reviews/{id}:
    get:
      tags:
        - User > Reviews
      summary: Show
    put:
      tags:
        - User > Reviews
      summary: Update
  /banners:
    get:
      tags:
        - Banners
      summary: List
  /banners/{id}:
    get:
      tags:
        - Banners
      summary: Show
  /cuisines:
    get:
      tags:
        - Cuisines
      summary: List
  /cuisines/{id}:
    get:
      tags:
        - Cuisines
      summary: Show
  /checkouts/{token}/{id}:
    post:
      tags:
        - Checkouts
      summary: Process
      operationId: processTheCheckout
  /static/about:
    get:
      tags:
        - Static > Pages
      summary: About
  /static/privacy-policy:
    get:
      tags:
        - Static > Pages
      summary: Privacy Policy
  /static/content-policy:
    get:
      tags:
        - Static > Pages
      summary: Content Policy
  /static/terms-of-services:
    get:
      tags:
        - Static > Pages
      summary: Terms Of Services
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer