openapi: 3.0.0
info:
  title: Wonderbites App
  description: ""
  version: v1.0
security:
  - BearerAuth: []
servers:
  - description: Wonderbites API for public website and mobile applications.
    url: https://api.wonderbites.app/api

tags:
  - name: Auth
    description: Application authentication endpoints.
  - name: Categories
    description: Application authentication endpoints.
  - name: Products
    description: Application authentication endpoints.
  - name: Cuisines
    description: Application authentication endpoints.
  - name: Advertisements
    description: Application authentication endpoints.
  - name: Checkouts
    description: Application authentication endpoints.
  - name: Auth > User
    description: Application authentication endpoints.
  - name: User > Profile
    description: Application authentication endpoints.
  - name: User > Avatar
    description: Application authentication endpoints.
  - name: User > Address
    description: Application authentication endpoints.
  - name: User > Coupons
    description: Application authentication endpoints.
  - name: User > Cart
    description: Application authentication endpoints.
  - name: User > Wonderpoints
    description: Application authentication endpoints.
  - name: User > Orders
    description: Application authentication endpoints.
  - name: User > Reviews
    description: Application authentication endpoints.
  - name: User > Feedbacks
    description: Application authentication endpoints.
  - name: User > Wishlist
    description: Application authentication endpoints.
  - name: Media
    description: Application authentication endpoints.
  - name: Static > Pages
    description: Application authentication endpoints.
paths:
  /login:
    post:
      tags:
        - Auth
      security: []
      summary: Login
      description: Login users via their email|mobile and password.
      operationId: loginToApp
  /register:
    post:
      tags:
        - Auth
      security: []
      summary: Register
      description: Register users to the wonderbites cloud.
      operationId: registerToApp
  /logout:
    post:
      tags:
        - Auth
      security:
        - BearerAuth:
            - token:revoke
      summary: Logout
      description: Revoke logged in user's auth token.
      operationId: logoutFromApp
  /users/auth:
    get:
      tags:
        - Auth > User
      security:
        - BearerAuth:
            - auth:view
      summary: Get
      description: Get the authenticated user data based on the authentication token.
      operationId: authenticatedUser
  /users/avatar:
    put:
      tags:
        - User > Avatar
      security:
        - BearerAuth:
            - avatar:update
      summary: Update
      description: Update user's profile avatar.
      operationId: userAvatar
  /users/{id}:
    put:
      tags:
        - User > Profile
      security:
        - BearerAuth:
            - auth:update
      summary: Update
      description: Update user profile data.
      operationId: updateUserByID
    get:
      tags:
        - User > Profile
      security:
        - BearerAuth:
            - auth:view
      summary: Detail
      description: Get the authenticated user data based on the authentication token.
      operationId: showUserByID
  /addresses:
    get:
      tags:
        - User > Address
      security:
        - BearerAuth:
            - address:list
      summary: List
      operationId: getAddressesList
    post:
      tags:
        - User > Address
      security:
        - BearerAuth:
            - address:create
      summary: Create
      operationId: storeAddressesList
  /addresses/{id}:
    get:
      tags:
        - User > Address
      security:
        - BearerAuth:
            - address:view
      summary: Show
      operationId: getAddressesById
    put:
      tags:
        - User > Address
      security:
        - BearerAuth:
            - address:edit
            - address:update
      summary: Update
      operationId: putAddressesById
    patch:
      tags:
        - User > Address
      security:
        - BearerAuth:
            - address:edit
            - address:update
      summary: Update
      operationId: patchAddressesById
    delete:
      tags:
        - User > Address
      security:
        - BearerAuth:
            - address:delete
            - address:destroy
      summary: Delete
      description: Request to delete the user address.
      operationId: deleteAddressesById
  /categories:
    get:
      tags:
        - Categories
      security: []
      summary: List
      description: By passing in the appropriate options, you can search for available categories in the system.
  /categories/{id}:
    get:
      tags:
        - Categories
      security: []
      summary: View
      description: By passing in the appropriate options, you can search for available categories in the system.
      operationId: showCategory
  /products:
    get:
      tags:
        - Products
      security: []
      summary: List
      description: By passing in the appropriate options, you can search for available products in the system.
      operationId: searchProducts
  /products/{id}:
    get:
      tags:
        - Products
      security: []
      summary: Show
      description: By passing in the appropriate options, you can search for available products in the system.
      operationId: showProducts
  /cart:
    put:
      tags:
        - User > Cart
      summary: Update
    patch:
      tags:
        - User > Cart
      summary: Update
    get:
      tags:
        - User > Cart
      summary: Detail
  /wonderpoints:
    get:
      tags:
        - User > Wonderpoints
      summary: Detail
  /wonderpoints/avail:
    get:
      tags:
        - User > Wonderpoints
      summary: Balance
  /wishlists:
    get:
      tags:
        - User > Wishlist
      summary: Detail
    put:
      tags:
        - User > Wishlist
      summary: Update
  /wishlists/clean:
    post:
      tags:
        - User > Wishlist
      summary: Clean
  /feedbacks:
    get:
      tags:
        - User > Feedbacks
      summary: List
    post:
      tags:
        - User > Feedbacks
      summary: Store
  /feedbacks/{id}:
    get:
      tags:
        - User > Feedbacks
      summary: Show
    put:
      tags:
        - User > Feedbacks
      summary: Update
    patch:
      tags:
        - User > Feedbacks
      summary: Update
    delete:
      tags:
        - User > Feedbacks
      summary: Delete
  /coupons/apply:
    post:
      tags:
        - User > Coupons
      summary: Redeem
  /coupons/remove:
    post:
      tags:
        - User > Coupons
      summary: Redeem
  /orders:
    get:
      tags:
        - User > Orders
      summary: List
  /orders/{id}:
    get:
      tags:
        - User > Orders
      summary: Detail
  /orders/{id}/cancel:
    put:
      tags:
        - User > Orders
      summary: Cancel
  /reviews:
    get:
      tags:
        - User > Reviews
      summary: List
    post:
      tags:
        - User > Reviews
      summary: Store
  /reviews/{id}:
    get:
      tags:
        - User > Reviews
      summary: Show
    put:
      tags:
        - User > Reviews
      summary: Update
  /advertisements:
    get:
      tags:
        - Advertisements
      summary: List
  /advertisements/{id}:
    get:
      tags:
        - Advertisements
      summary: Show
  /cuisines:
    get:
      tags:
        - Cuisines
      summary: List
  /cuisines/{id}:
    get:
      tags:
        - Cuisines
      summary: Show
  /checkouts:
    post:
      tags:
        - Checkouts
      summary: Process
  /static/about:
    get:
      tags:
        - Static > Pages
      summary: About
  /static/privacy-policy:
    get:
      tags:
        - Static > Pages
      summary: Privacy Policy
  /static/content-policy:
    get:
      tags:
        - Static > Pages
      summary: Content Policy
  /static/terms-of-services:
    get:
      tags:
        - Static > Pages
      summary: Terms Of Services
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer