---
openapi: 3.0.0
info:
  title: Wonderbites App
  description: ""
  version: v1.0
servers:
  - url: https://virtserver.swaggerhub.com/iyashpal/WonderbitesApp/v1.0
    description: SwaggerHub API Auto Mocking
paths:
  /api/categories:
    get:
      tags:
        - Categories
      summary: List
      description: |
        By passing in the appropriate options, you can search for available categories in the system.
      operationId: searchCategory
      parameters:
        - name: type
          in: query
          description: The type of category (i.e. product, ingredient, cuisine etc.)
          style: form
          required: false
          explode: true
          schema:
            type: string
        - name: with
          in: query
          description: Pass an optional strings of category
          required: false
          schema:
            type: array
            items: {}
      responses:
        "200":
          description: Search results matching criteria

components:
  schemas:
    Categories:
      required:
        - type
        - name
      type: object
      properties:
        id:
          type: integer
          example: 1
        type:
          type: string
          example: Product | Ingredient | Cuisine etc.
        parent:
          type: integer
          description: Reference to parent category.
          example: 0
        description:
          type: string
          description: Category description.
        status:
          type: integer
        created_at:
          type: string
        updated_at:
          type: string
        
    Users:
      required:
        - email
        - first_name
        - id
        - last_name
        - mobile
        - password
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Doe
        email:
          type: string
          example: john.doe@example.com
        password:
          type: string
          example: password
        image_path:
          type: string
          example: /storage/avatar.png
        address_id:
          type: number
          example: 1
        remember_me_token:
          type: string
        mobile:
          type: string
          example: 0123456798
        status:
          type: integer
        language:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        deleted_at:
          type: string
    Addresses:
      required:
        - city
        - first_name
        - last_name
        - phone
        - street
        - type
      type: object
      properties:
        id:
          type: string
          example: ACME Corporation
        user_id:
          type: string
          format: url
          example: https://www.acme-corp.com
        first_name:
          type: string
          example: 408-867-5309
        last_name:
          type: string
        street:
          type: string
        city:
          type: string
        phone:
          type: string
        location:
          type: object
          example:
            lat: 2135467
            lng: -56864564
        created_at:
          type: string
        updated_at:
          type: string
        deleted_at:
          type: string
