{
  "openapi": "3.0.0",
  "info": {
    "title": "Wonderbites App",
    "description": "",
    "version": "v1.0",
    "license": {
      "name": "MIT",
      "url": "https://api.wonderbites.app"
    }
  },
  "security": [
    {
      "BearerAuth": []
    }
  ],
  "servers": [
    {
      "description": "Wonderbites API for public website and mobile applications.",
      "url": "https://api.wonderbites.app/api"
    }
  ],
  "paths": {
    "/login": {
      "post": {
        "tags": [
          "Auth"
        ],
        "security": [],
        "summary": "Login",
        "description": "Login users via their email|mobile and password.",
        "operationId": "loginToApp"
      }
    },
    "/register": {
      "post": {
        "tags": [
          "Auth"
        ],
        "security": [],
        "summary": "Register",
        "description": "Register users to the wonderbites cloud.",
        "operationId": "registerToApp"
      }
    },
    "/logout": {
      "post": {
        "tags": [
          "Auth"
        ],
        "security": [
          {
            "BearerAuth": [
              "token:revoke"
            ]
          }
        ],
        "summary": "Logout",
        "description": "Revoke logged in user's auth token.",
        "operationId": "logoutFromApp"
      }
    },
    "/users/auth": {
      "get": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "BearerAuth": [
              "auth:view"
            ]
          }
        ],
        "summary": "Auth User",
        "description": "Get the authenticated user data based on the authentication token.",
        "operationId": "authenticatedUser"
      }
    },
    "/users/avatar": {
      "put": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "BearerAuth": [
              "avatar:update"
            ]
          }
        ],
        "summary": "Profile Avatar",
        "description": "Update user's profile avatar.",
        "operationId": "userAvatar"
      }
    },
    "/users/{id}": {
      "put": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "BearerAuth": [
              "auth:update"
            ]
          }
        ],
        "summary": "Update Profile",
        "description": "Update user profile data.",
        "operationId": "updateUserByID"
      },
      "get": {
        "tags": [
          "Users"
        ],
        "security": [
          {
            "BearerAuth": [
              "auth:view"
            ]
          }
        ],
        "summary": "User Profile",
        "description": "Get the authenticated user data based on the authentication token.",
        "operationId": "showUserByID"
      }
    },
    "/addresses": {
      "get": {
        "tags": [
          "Addresses"
        ],
        "security": [
          {
            "BearerAuth": [
              "address:list"
            ]
          }
        ],
        "summary": "Browse Addresses",
        "operationId": "getAddressesList"
      },
      "post": {
        "tags": [
          "Addresses"
        ],
        "security": [
          {
            "BearerAuth": [
              "address:create"
            ]
          }
        ],
        "summary": "Create Address",
        "operationId": "storeAddressesList"
      }
    },
    "/addresses/{id}": {
      "get": {
        "tags": [
          "Addresses"
        ],
        "security": [
          {
            "BearerAuth": [
              "address:view"
            ]
          }
        ],
        "summary": "View Address",
        "operationId": "getAddressesById"
      },
      "put": {
        "tags": [
          "Addresses"
        ],
        "security": [
          {
            "BearerAuth": [
              "address:edit", "address:update"
            ]
          }
        ],
        "summary": "Update Address",
        "operationId": "putAddressesById"
      },
      "patch": {
        "tags": [
          "Addresses"
        ],
        "security": [
          {
            "BearerAuth": [
              "address:edit", "address:update"
            ]
          }
        ],
        "summary": "Update Address",
        "operationId": "patchAddressesById"
      },
      "delete": {
        "tags": [
          "Addresses"
        ],
        "security": [
          {
            "BearerAuth": [
              "address:delete", "address:destroy"
            ]
          }
        ],
        "summary": "Delete Address",
        "description": "Request to delete the user address.",
        "operationId": "deleteAddressesById"
      }
    },
    "/categories": {
      "get": {
        "tags": [
          "Categories"
        ],
        "summary": "List",
        "description": "By passing in the appropriate options, you can search for available categories in the system.",
        "operationId": "searchCategory"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  }
}
