import {
  CogIcon as Cog,
  StarIcon as Star,
  HomeIcon as Home,
  PlusIcon as Plus,
  TrashIcon as Trash,
  UsersIcon as Users,
  UserCircleIcon as UserCircle,
  PhotoIcon as Photo,
  XMarkIcon as XMark,
  ClockIcon as Clock,
  TicketIcon as Ticket,
  FolderIcon as Folder,
  UserIcon as User,
  BookOpenIcon as BookOpen,
  UserGroupIcon as UserGroup,
  ChevronRightIcon as ChevronRight,
  DocumentTextIcon as DocumentText,
  CalendarDaysIcon as CalendarDays,
  CloudArrowUpIcon as CloudArrowUp,
  ChevronUpDownIcon as ChevronUpDown,
  RectangleStackIcon as RectangleStack,
  MagnifyingGlassIcon as MagnifyingGlass,
  ExclamationTriangleIcon as ExclamationTriangle,
  ArrowTopRightOnSquareIcon as ArrowTopRightOnSquare,
  ChatBubbleOvalLeftEllipsisIcon as ChatBubbleOvalLeftEllipsis,

  BookmarkIcon as Bookmark,
  EnvelopeIcon as Envelope,
  EyeIcon as Eye,
  HashtagIcon as Hashtag,
  PencilSquareIcon as PencilSquare,
  LinkIcon as Link,
  CurrencyDollarIcon as CurrencyDollar,
} from '@heroicons/react/24/outline'

export {
  CurrencyDollar,
  Link,
  Eye,
  Bookmark,
  Envelope,
  Hashtag,
  PencilSquare,
  Home,
  Star,
  Cog,
  Plus,
  Photo,
  Ticket,
  Folder,
  Clock,
  Trash,
  XMark,
  Users,
  BookOpen,
  UserGroup,
  User,
  UserCircle,
  CalendarDays,
  ChevronRight,
  DocumentText,
  CloudArrowUp,
  ChevronUpDown,
  RectangleStack,
  MagnifyingGlass,
  ExclamationTriangle,
  ArrowTopRightOnSquare,
  ChatBubbleOvalLeftEllipsis,
}
