import {
  CogIcon as Cog,
  StarIcon as Star,
  HomeIcon as Home,
  PlusIcon as Plus,
  UserIcon as User,
  TrashIcon as Trash,
  UsersIcon as Users,
  PhotoIcon as Photo,
  XMarkIcon as XMark,
  ClockIcon as Clock,
  TicketIcon as Ticket,
  FolderIcon as Folder,
  BookOpenIcon as BookOpen,
  UserGroupIcon as UserGroup,
  ChevronUpIcon as ChevronUp,
  UserCircleIcon as UserCircle,
  ChevronDownIcon as ChevronDown,
  ChevronRightIcon as ChevronRight,
  DocumentTextIcon as DocumentText,
  CalendarDaysIcon as CalendarDays,
  CloudArrowUpIcon as CloudArrowUp,
  ChevronUpDownIcon as ChevronUpDown,
  ArrowLongLeftIcon as ArrowLongLeft,
  CloudArrowDownIcon as CloudArrowDown,
  RectangleStackIcon as RectangleStack,
  MagnifyingGlassIcon as MagnifyingGlass,
  Bars3BottomLeftIcon as Bars3BottomLeft,
  ExclamationTriangleIcon as ExclamationTriangle,
  ArrowTopRightOnSquareIcon as ArrowTopRightOnSquare,
  ChatBubbleOvalLeftEllipsisIcon as ChatBubbleOvalLeftEllipsis,
  EllipsisVerticalIcon as EllipsisVertical,
  BookmarkIcon as Bookmark,
  EnvelopeIcon as Envelope,
  EyeIcon as Eye,
  HashtagIcon as Hashtag,
  PencilSquareIcon as PencilSquare,
  LinkIcon as Link,
  TagIcon as Tag,
  InformationCircleIcon as InformationCircle,
  QueueListIcon as QueueList,
  CheckCircleIcon as CheckCircle,
  CurrencyDollarIcon as CurrencyDollar,
} from '@heroicons/react/24/outline'

export {
  InformationCircle,
  QueueList,
  CheckCircle,
  ArrowLongLeft,
  EllipsisVertical,
  ChevronUp,
  ChevronDown,
  CurrencyDollar,
  Link,
  Eye,
  Bookmark,
  Envelope,
  Hashtag,
  Tag,
  PencilSquare,
  Home,
  Star,
  Cog,
  Plus,
  Photo,
  Ticket,
  Folder,
  Clock,
  Trash,
  XMark,
  Users,
  BookOpen,
  UserGroup,
  User,
  UserCircle,
  CalendarDays,
  ChevronRight,
  DocumentText,
  CloudArrowUp,
  CloudArrowDown,
  Bars3BottomLeft,
  ChevronUpDown,
  RectangleStack,
  MagnifyingGlass,
  ExclamationTriangle,
  ArrowTopRightOnSquare,
  ChatBubbleOvalLeftEllipsis,
}
