import {
  CogIcon as Cog,
  StarIcon as Star,
  HomeIcon as Home,
  PlusIcon as Plus,
  TrashIcon as Trash,
  UsersIcon as Users,
  PhotoIcon as Photo,
  XMarkIcon as XMark,
  ClockIcon as Clock,
  TicketIcon as Ticket,
  FolderIcon as Folder,
  BookOpenIcon as BookOpen,
  UserGroupIcon as UserGroup,
  ChevronRightIcon as ChevronRight,
  DocumentTextIcon as DocumentText,
  CalendarDaysIcon as CalendarDays,
  CloudArrowUpIcon as CloudArrowUp,
  ChevronUpDownIcon as ChevronUpDown,
  RectangleStackIcon as RectangleStack,
  MagnifyingGlassIcon as MagnifyingGlass,
  ExclamationTriangleIcon as ExclamationTriangle,
  ArrowTopRightOnSquareIcon as ArrowTopRightOnSquare,
  ChatBubbleOvalLeftEllipsisIcon as ChatBubbleOvalLeftEllipsis,
  BookmarkIcon as Bookmark,
  EnvelopeIcon as Envelope,
  EyeIcon as Eye,
  HashtagIcon as Hashtag,
  PencilSquareIcon as PencilSquare,
} from '@heroicons/react/24/solid'

export {
  Home,
  Star,
  Cog,
  Plus,
  Photo,
  Ticket,
  Folder,
  Clock,
  Trash,
  XMark,
  Users,
  Eye,
  Bookmark,
  Envelope,
  Hashtag,
  PencilSquare,
  BookOpen,
  UserGroup,
  CalendarDays,
  ChevronRight,
  DocumentText,
  CloudArrowUp,
  ChevronUpDown,
  RectangleStack,
  MagnifyingGlass,
  ExclamationTriangle,
  ArrowTopRightOnSquare,
  ChatBubbleOvalLeftEllipsis,
}
