import {
  CogIcon as Cog,
  StarIcon as Star,
  HomeIcon as Home,
  PlusIcon as Plus,
  TrashIcon as Trash,
  UsersIcon as Users,
  PhotoIcon as Photo,
  XMarkIcon as XMark,
  ClockIcon as Clock,
  TicketIcon as Ticket,
  FolderIcon as Folder,
  BookOpenIcon as BookOpen,
  UserGroupIcon as UserGroup,
  ChevronUpIcon as ChevronUp,
  ChevronDownIcon as ChevronDown,
  ChevronRightIcon as ChevronRight,
  DocumentTextIcon as DocumentText,
  CalendarDaysIcon as CalendarDays,
  CloudArrowUpIcon as CloudArrowUp,
  ArrowLongLeftIcon as ArrowLongLeft,
  CloudArrowDownIcon as CloudArrowDown,
  ChevronUpDownIcon as ChevronUpDown,
  RectangleStackIcon as RectangleStack,
  MagnifyingGlassIcon as MagnifyingGlass,
  EllipsisVerticalIcon as EllipsisVertical,
  ExclamationTriangleIcon as ExclamationTriangle,
  ArrowTopRightOnSquareIcon as ArrowTopRightOnSquare,
  ChatBubbleOvalLeftEllipsisIcon as ChatBubbleOvalLeftEllipsis,
  BookmarkIcon as Bookmark,
  EnvelopeIcon as Envelope,
  EyeIcon as Eye,
  TagIcon as Tag,
  HashtagIcon as Hashtag,
  Bars3BottomLeftIcon as Bars3BottomLeft,
  LinkIcon as Link,
  QueueListIcon as QueueList,
  CheckCircleIcon as CheckCircle,
  CurrencyDollarIcon as CurrencyDollar,
  PencilSquareIcon as PencilSquare,
  InformationCircleIcon as InformationCircle,
} from '@heroicons/react/24/solid'

export {
  InformationCircle,
  QueueList,
  CheckCircle,
  ArrowLongLeft,
  EllipsisVertical,
  ChevronUp,
  ChevronDown,
  CurrencyDollar,
  Link,
  Home,
  Star,
  Cog,
  Tag,
  Plus,
  Photo,
  Ticket,
  Folder,
  Clock,
  Trash,
  XMark,
  Users,
  Eye,
  Bookmark,
  Envelope,
  Hashtag,
  PencilSquare,
  BookOpen,
  UserGroup,
  CalendarDays,
  ChevronRight,
  DocumentText,
  CloudArrowUp,
  CloudArrowDown,
  ChevronUpDown,
  RectangleStack,
  Bars3BottomLeft,
  MagnifyingGlass,
  ExclamationTriangle,
  ArrowTopRightOnSquare,
  ChatBubbleOvalLeftEllipsis,
}
