export {default as FeedbackIcon} from './FeedbackIcon'
export {default as ReviewsIcon} from './ReviewsIcon'
export {default as DashboardIcon} from './DashboardIcon'
export {default as WonderPointsIcon} from './WonderPointsIcon'
export {default as ForwardSlashIcon} from './ForwardSlashIcon'
