name: Tests

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 17.x, 18.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Execute tests
        run: node ace test